# Rellena el docker-compose para que puedan interactuar la aplicación de node con la base de datos de mongodb
version: '3.3'

services:

  node:
    build: node
    restart: always
    ports:
     - 8080:8080

  mongodb:
      build: mongodb
      restart: always
      volumes:
           - ./mongodb_data:/data/db
      environment:
            MONGO_INITDB_ROOT_USERNAME: user
            MONGO_INITDB_ROOT_PASSWORD: test123
            MONGO_INITDB_DATABASE: test
      ports:
       - 27017:27017
